<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>csharp-peer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fomoxa.Net" Version="0.1.0" />
    <PackageReference Include="Fomoxa.Attributes" Version="0.1.0" />
  </ItemGroup>

</Project>
